name: github action file to test basic code on multiple versions of py

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8,3.9]

    steps:
    - uses: actions/checkout@v3
    - name: setting up python
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}

    - name: Installing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py